apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: wordpress
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Welcome1
  MYSQL_USER: wp_user
  MYSQL_PASSWORD: Welcome1
  MYSQL_DATABASE: wordpress

